Please use the Anaconda Navigator and open the IPYNB file in the Jupyter Notebook.
Ensure that the DataSet and the IPYNB file that you are opening are both in the same folder.
Hope this helps!

Here is the LINK TO THE DATASET:

https://drive.google.com/file/d/1MRGBfX3TBmzoMdHzQSjgDSO4AQp3uM0U/view?usp=sharing
https://drive.google.com/file/d/1ixuMCHxKHhUAFOYy9lUL8kiKfYc4KtOx/view?usp=drive_link
